### ISSUE TITLE
MWFilters are only inclued in the source of MRCPP

### ISSUE THREAD

**Issue by bjorgve** [MRChemSoft/mrcpp#103]
The `MWFilters` used when running `mrchem` are located in `mrcpp/share/mwfilters`. So they are not available if `mrcpp` is removed from the system.

**Comment by stigrj** [comment]
Is it not installed with ``make install``?

**Comment by stigrj** [comment]
No, indeed this does not seem to be the case. Also the SAD input files for the initial guess needs to be installed under `share/`

**Comment by robertodr** [comment]
Anything else that should be installed and isn't? @bjorgve and I can prepare a patch easily.

**Comment by robertodr** [comment]
Note that there will always be an inconsistency between install and source trees when it comes to `MW_FILTER_DIR` in `config.h`. I can't think of a better way to bake in this info into the library...

**Comment by stigrj** [comment]
I think `mrcpp/share/mwfilters` and `mrchem/share/sad_basis` are the two things missing

**Comment by stigrj** [comment]
So it's not possible to get something that works both for the build and install trees at the same time? Is it not possible to reconfigure `config.h` at `make install`?

**Comment by robertodr** [comment]
OK, yes, I can patch it up at install time. It gets trickier with the conda package, but that's a separate issue.

**Comment by robertodr** [comment]
Even patching `config.h` is problematic (just tried and failed) The compile-time value of `MW_FILTER_DIR` is baked into the library since it's used in `MWFilter.cpp`. How inconvenient would it be to pass that as an input to MRCPP?

**Comment by stigrj** [comment]
Is it possible to use a relative path? Should be the same in `build` and `install`

**Comment by robertodr** [comment]
I don't know :thinking:

**Comment by stigrj** [comment]
Wait! There should be a `INSTALL_FILTERS=on/off` cmake option to mrcpp

**Comment by robertodr** [comment]
Yes, that's where we started on this rabbithole. If you set that, then the tests fail, 'cause `MW_FILTER_DIR` is hardcoded to the _install tree_.

**Comment by robertodr** [comment]
Look at #105 @bjorgve has a solution that, I think, will make everyone happy.

**Comment by robertodr** [comment]
This was fixed with #112
