### ISSUE TITLE
Derivative operator error message

### ISSUE THREAD

**Issue by stigrj** [MRChemSoft/mrcpp#54]
Construction of derivative operator in a world with more than 2x2x2 root boxes produces the error message "This translation should not occur". Seems non-fatal.

**Comment by bjorgve** [comment]
Related to this: When to many root boxes are used mrcpp crashes with useless error messages.

We run into problmes when the number of root boxes are larger than the allocation size located in
SerialFunctionTree.cpp

**Comment by stigrj** [comment]
The error message was harmless and have been removed in #68.
